name: build

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_test.txt
    - name: Test
      run: |
        coverage run -m pytest -k 'not shell'
        coverage xml -i
    - name: fix code coverage paths
      run: |
        sed -i 's/\/home\/runner\/work\/sonar\/sonar\//\/github\/workspace\//g' coverage.xml
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Codecov
      uses: codecov/codecov-action@v1.0.14
      with:
        # Path to coverage file to upload
        file: coverage.xml
        # Specify whether or not CI build should fail if Codecov runs into an error during upload
        fail_ci_if_error: true
